import ToasterProvider from "components/providers/ToasterProvider";
import "../public/style/globals.scss";
import { Inter } from "next/font/google";
import ReactQueryProvider from "components/providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ToasterProvider>
            {children}
          </ToasterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
